### ISSUE TITLE
Is it possible to use "Natural identifiers" approach with EF Core 5?

### ISSUE THREAD

**Issue by BogdanGirnyk** [sygnowskip/sygnowskip.github.io#8]
I tried to use this approach with EF Core 5 but there are huge api changes since version 3 (e g SqlServerMigrationsAnnotationProvider is completely different).

**Comment by sygnowskip** [comment]
@BogdanGirnyk yes, it is still possible to use these identifiers with EF Core 5.x - check this out https://github.com/sygnowskip/modular-monolith/tree/master/Source/Hexure.EntityFrameworkCore

But I'm no longer using EF Core migrations, I've switched to https://dbup.readthedocs.io/en/latest/ some time ago ;)

**Comment by BogdanGirnyk** [comment]
@sygnowskip  thank you very much for that reference!
Did I understand correctly that Id autoincrement there is configured manually in sql script without leveraging EF Core mechanisms?

**Comment by sygnowskip** [comment]
@BogdanGirnyk yes

From my experience, EF Core migrations are very hard to maintain in a projects with multiple developers / features developed simultaneously, raw SQL scripts and DbUp are much, much easier 😃
